# Generated by Django 6.0.6 on 2026-06-07 20:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='trip',
            name='status',
            field=models.CharField(choices=[('planning', 'Planejamento'), ('travelling', 'Em viagem'), ('finished', 'Finalizada')], default='planning', max_length=20),
        ),
        migrations.AlterField(
            model_name='trip',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
