# Generated by Django 6.0.6 on 2026-06-07 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_remove_trip_updated_at_trip_status_alter_trip_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='country_flag',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='trip',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='trip_covers/'),
        ),
    ]
