# Generated by Django 6.0.6 on 2026-06-07 23:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trips', '0003_trip_country_flag_trip_cover_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('passport', 'Passaporte'), ('insurance', 'Seguro'), ('hotel', 'Hotel'), ('flight', 'Passagem'), ('train', 'Trem'), ('ticket', 'Ingresso'), ('other', 'Outros')], max_length=50)),
                ('file', models.FileField(upload_to='documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='trips.trip')),
            ],
        ),
    ]
