# Generated by Django 6.0.6 on 2026-06-09 00:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
        ('trips', '0003_trip_country_flag_trip_cover_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='traveldocument',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='traveldocument',
            name='category',
            field=models.CharField(choices=[('passport', 'Passaporte'), ('id_card', 'Identidade/RG/CNH'), ('insurance', 'Seguro'), ('hotel', 'Hotel'), ('flight', 'Passagem'), ('train', 'Trem'), ('ticket', 'Ingresso'), ('other', 'Outros')], max_length=50),
        ),
        migrations.AlterField(
            model_name='traveldocument',
            name='trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='trips.trip'),
        ),
    ]
