# Generated by Django 6.0.6 on 2026-06-07 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trips', '0003_trip_country_flag_trip_cover_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('income', 'Entrada'), ('expense', 'Saída')], max_length=20)),
                ('category', models.CharField(choices=[('flight', 'Passagem'), ('hotel', 'Hospedagem'), ('food', 'Alimentação'), ('transport', 'Transporte'), ('shopping', 'Compras'), ('other', 'Outros')], max_length=30)),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='trips.trip')),
            ],
        ),
    ]
